// file: src/infrastructure/logger/LOG_EVENTS.ts

export const LOG_EVENTS = {
  // Server events
  SERVER_STARTED: "SERVER_STARTED",
  SERVER_SHUTDOWN: "SERVER_SHUTDOWN",
  SERVER_CLOSED: "SERVER_CLOSED",

  // SQS Consumer events
  SQS_CONSUMER_DISABLED: "SQS_CONSUMER_DISABLED",
  SQS_CONSUMER_STARTED: "SQS_CONSUMER_STARTED",
  SQS_CONSUMER_STOPPED: "SQS_CONSUMER_STOPPED",
  SQS_MESSAGE_RECEIVED: "SQS_MESSAGE_RECEIVED",
  SQS_CONSUMER_ERROR: "SQS_CONSUMER_ERROR",
  SQS_PROCESSING_ERROR: "SQS_PROCESSING_ERROR",

  // HTTP events
  HTTP_REQUEST: "HTTP_REQUEST",

  // Database events
  DATABASE_ERROR: "DATABASE_ERROR",

  // Projection update events
  PROJECTION_UPDATE_RECEIVED: "PROJECTION_UPDATE_RECEIVED",
  PROJECTION_UPDATE_ERROR: "PROJECTION_UPDATE_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MANIFEST_READ: "MANIFEST_READ",
  JSON_FILE_PROCESSED: "JSON_FILE_PROCESSED",
  JSON_FILE_ERROR: "JSON_FILE_ERROR",
  SERIES_SAVED: "SERIES_SAVED",
} as const;

